### ISSUE TITLE
Presence of labels within downloaded abstracts

### ISSUE THREAD

**Issue by c-hawthorne** [skoval/RISmed#19]
Hi, 

Downloaded abstracts appear to have labels in the text. 

> library(devtools)
> install_github(repo = "https://github.com/skoval/RISmed")
> library(RISmed)
> query <- EUtilsSummary('"Income"[MeSH]', retmax = 50)
> results <- EUtilsGet(x = query, type = "efetch", db = "pubmed")
> abstracts <- AbstractText(results)
> names(abstracts) <- PMID(results)
> abstracts

Thank you.

**Comment by skoval** [comment]
I've made an update to extract the label description and include those headings in all caps. Unstructured abstracts should not be affected.

**Comment by bes828** [comment]
@skoval 
thanks for working on this great package. 
is there a way to avoid getting these labels within the abstract? I am trying some text summarization / basic nlp stuff on the abstracts and I am unable to reproduce the results with my previous codes. 
I mean if there is an argument or something to provide an option of extraction without the labels. 

thanks again

**Comment by skoval** [comment]
Rather than removing them from the source, you could try something like the following:

```r
stringr::str_remove_all(x@AbstractText, "[A-Z]+\\:")
```
since all of the labels in the current commit will be an upper case word followed by a colon. There is some chance that this syntax might appear within the body of the text, rather than a label. I would expect that to be rare but if it is frequent enough that it presents a problem for you, please post another issue

**Comment by bes828** [comment]
@skoval 
thank you
I tried the regex you sent but I am still unable to remove the labels/categories
I posted another issue with a reproducible example as you suggested https://github.com/skoval/RISmed/issues/20

thank you
