### ISSUE TITLE
Error in EUtilsSummary() function

### ISSUE THREAD

**Issue by Rnewbie** [skoval/RISmed#4]
Hi, 

I was following the Bioinformatics with R Coolbook, in the first chapter, it used the EutilsSummary function to get customised query. Instead of getting the data object, I get an error 
```
> cancer <- EUtilsSummary("cancer[ti]", type = "research", db = "pubmed")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open: HTTP status was '404 Not Found'
```
Thanks in advance.

**Comment by skoval** [comment]
I think the issue is with the "type" argument. Try:

cancer <- EUtilsSummary("cancer[ti]", db = "pubmed")

The "type" refers to the type of E-utility. The default is "esearch" (maybe auto-correct changed esearch to research?).  This is the most common type, but you can find details about other types at: http://www.ncbi.nlm.nih.gov/books/NBK25499/

**Comment by Rnewbie** [comment]
Thank you. It works wonderfully. I like API.

**Comment by skoval** [comment]
Great. It looks like the authors of the "R Cookbook" made an error with the type = "research". Will send them a message about this. Thanks for bringing this to my attention.

**Comment by Rnewbie** [comment]
Thank you again skoval. The dog look so cute.
